# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arith.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61rith.proto\x12\x04grpc\"*\n\x0c\x41rithRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1f\n\rArithResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32v\n\x05\x41rith\x12\x35\n\x08XiangJia\x12\x12.grpc.ArithRequest\x1a\x13.grpc.ArithResponse\"\x00\x12\x36\n\tXiangJian\x12\x12.grpc.ArithRequest\x1a\x13.grpc.ArithResponse\"\x00\x42\x06Z\x04grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arith_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004grpc'
  _globals['_ARITHREQUEST']._serialized_start=21
  _globals['_ARITHREQUEST']._serialized_end=63
  _globals['_ARITHRESPONSE']._serialized_start=65
  _globals['_ARITHRESPONSE']._serialized_end=96
  _globals['_ARITH']._serialized_start=98
  _globals['_ARITH']._serialized_end=216
# @@protoc_insertion_point(module_scope)
