// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: micro/proto/rpcapi/common.proto

package rpcapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	model "github.com/wh1t3zer/Hawkeye-Go/micro/proto/model"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Victim service

type VictimService interface {
	Communication(ctx context.Context, in *model.Request, opts ...client.CallOption) (*model.Response, error)
}

type victimService struct {
	c    client.Client
	name string
}

func NewVictimService(name string, c client.Client) VictimService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "rpcapi"
	}
	return &victimService{
		c:    c,
		name: name,
	}
}

func (c *victimService) Communication(ctx context.Context, in *model.Request, opts ...client.CallOption) (*model.Response, error) {
	req := c.c.NewRequest(c.name, "Victim.Communication", in)
	out := new(model.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Victim service

type VictimHandler interface {
	Communication(context.Context, *model.Request, *model.Response) error
}

func RegisterVictimHandler(s server.Server, hdlr VictimHandler, opts ...server.HandlerOption) error {
	type victim interface {
		Communication(ctx context.Context, in *model.Request, out *model.Response) error
	}
	type Victim struct {
		victim
	}
	h := &victimHandler{hdlr}
	return s.Handle(s.NewHandler(&Victim{h}, opts...))
}

type victimHandler struct {
	VictimHandler
}

func (h *victimHandler) Communication(ctx context.Context, in *model.Request, out *model.Response) error {
	return h.VictimHandler.Communication(ctx, in, out)
}
