# This is base config

[base]
    debug_mode="debug"
    time_location="Asia/Chongqing"

[http]
    addr =":8700"                       # 监听地址, default ":8700"
    read_timeout = 10                   # 读取超时时长
    write_timeout = 10                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度
    allow_ip = [                        # 白名单ip列表
        "127.0.0.1",
        "192.168.10.102",
        "10.10.240.80"                  # 添加内网IP
    ]

[session]
    redis_server = "127.0.0.1:6379"   #redis session server
    redis_password = ""

[log]
    log_level = "trace"         #日志打印最低级别
    [log.file_writer]           #文件写入配置
        on = true
        log_path = "./logs/Hawkeye.inf.log"
        rotate_log_path = "./logs/Hawkeye.inf.log.%Y%M%D%H"
        wf_log_path = "./logs/Hawkeye.wf.log"
        rotate_wf_log_path = "./logs/Hawkeye.wf.log.%Y%M%D%H"
    [log.console_writer]        #工作台输出
        on = false
        color = false

[cluster]
    cluster_ip="192.168.10.102"
    cluster_port="8700"
    cluster_ssl_port="4880"

[swagger]
    title="Hawkeye swagger API"
    desc="This is a sample server celler server."
    host="192.168.10.102:8700"
    base_path=""
    version="1.0"
    # schemes="http,https"
    schemes = [
        "http",
        "https"
    ]